name: "BackdropCMS coding standards"
description: "Runs PHP_CodeSniffer on all files using the BackdropCMS ruleset."
inputs:
  php_version:
    description: "PHP version to run on"
    required: false
    type: string
    default: "8.3"
  fail_on_warnings:
    description: "Do not fail on standard warnings, only on errors."
    required: false
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: Setup PHP with CodeSniffer tool
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        tools: phpcs
        coverage: none

    # The checkout action refuses to put it outside, so we have to do it in
    # two steps.
    - name: Checkout coding standard
      uses: actions/checkout@v6
      with:
        repository: backdrop-ops/phpcs
        ref: 1.2.0
        path: phpcs

    - name: Move standard outside current dir
      shell: bash
      run: mv phpcs ..

    - name: Checkout code
      uses: actions/checkout@v6

    - name: Run phpcs
      shell: bash
      run: |
        : Prepare param and run phpcs
        PARAM='-n'
        if [[ ${{ inputs.fail_on_warnings }} == "true" ]]; then PARAM=''; fi
        phpcs --standard=../phpcs/Backdrop --report=../phpcs/Backdrop/Reports/Github.php --basepath=. $PARAM *
